### ISSUE TITLE
Global issues

### ISSUE THREAD

**Issue by jasongrout** [davidbrochart/akernel#4]
I'm curious how this interacts with `global` variables inside a function inside a cell, for example:

```python
a = 1

def f():
    global a
    a = 5

f()
print(a)
```

This prints out `5` with the current ipykernel, which is what I would expect.

**Comment by davidbrochart** [comment]
With akernel this prints out `1`, unless:
- the cell is divided in two:
```python
# cell 1
a = 1
```
```python
# cell 2
def f():
    global a
    a = 5

f()
print(a)
```
- or we use `nonlocal` instead of `global`:
```python
a = 1

def f():
    nonlocal a
    a = 5

f()
print(a)
```

**Comment by davidbrochart** [comment]
I'm thinking we could parse the code and look for assignments at the top-level, and declare every assigned variable as global.
Thanks for raising this issue @jasongrout !
